FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
                        build-essential \
                        cmake \
                        gcc \
    			g++ \
                        gdb \
                        git

WORKDIR	/apps
RUN git clone http://mod.lge.com/hub/timpani/sample-apps.git

WORKDIR	/apps/sample-apps/build
RUN cmake ..
RUN cmake --build .

ENTRYPOINT [ "/apps/sample-apps/build/sample_apps" ]
